apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-api-config
  namespace: ecommerce
data:
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
  ENABLE_METRICS: "true"
  PAGINATION_DEFAULT_LIMIT: "10"
  PAGINATION_MAX_LIMIT: "100"