apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-api-secret
  namespace: ecommerce
type: Opaque
data:
  # These are example values - in a real environment, use proper secrets management
  # Values are base64 encoded
  JWT_SECRET_KEY: "c3VwZXJzZWNyZXRrZXkxMjM="  # supersecretkey123
  DB_PASSWORD: "cGFzc3dvcmQxMjM="  # password123
  API_KEY: "YXBpa2V5MTIzNDU2Nzg5MA=="  # apikey1234567890