apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
    - name: ecommerce-alerts
      rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="ecommerce", container!=""}[5m])) by (pod) / sum(container_spec_cpu_quota{namespace="ecommerce", container!=""} / container_spec_cpu_period{namespace="ecommerce", container!=""}) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: Pod {{ $labels.pod }} in namespace ecommerce has high CPU usage (> 80%) for more than 5 minutes.

      - alert: HighMemoryUsage
        expr: sum(container_memory_working_set_bytes{namespace="ecommerce", container!=""}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="ecommerce", container!=""}) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: Pod {{ $labels.pod }} in namespace ecommerce has high memory usage (> 80%) for more than 5 minutes.

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{namespace="ecommerce", status=~"5.."}[5m])) by (service) / sum(rate(http_requests_total{namespace="ecommerce"}[5m])) by (service) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High HTTP error rate detected
          description: Service {{ $labels.service }} in namespace ecommerce has a high HTTP error rate (> 5%) for more than 2 minutes.

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace="ecommerce"}[5m])) by (service, le)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow response time detected
          description: Service {{ $labels.service }} in namespace ecommerce has a 95th percentile response time greater than 2 seconds for more than 5 minutes.

      - alert: PodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total{namespace="ecommerce"}[1h]) > 5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: Pod is crash looping
          description: Pod {{ $labels.pod }} in namespace ecommerce has restarted more than 5 times in the last hour.